openapi: 3.0.0
info:
  title: Data Library API
  version: 1.0.0
servers:
  - url: https://llmtalks.netlify.app
paths:
  /api/export/{id}:
    get:
      description: Export a record in various formats.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: format
          required: false
          schema:
            type: string
            enum:
              - json
              - text
              - markdown
      responses:
        '200':
          description: Exported data
        '404':
          description: Not found
  /api/library/{id}:
    get:
      description: Get a single record.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Stored record
        '404':
          description: Not found
    put:
      description: Update a record.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated record
        '404':
          description: Not found
    delete:
      description: Delete a record.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
  /api/library:
    get:
      description: List all stored records.
      responses:
        '200':
          description: Array of stored records
    post:
      description: Store a new record. Accepts JSON payload.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                payload:
                  type: object
      responses:
        '200':
          description: Stored record
    delete:
      description: Remove all records.
      responses:
        '204':
          description: Cleared
components: {}
tags: []

